name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Execute remote SSH commands using private key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 13.223.47.220
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEYS }}
          port: 22
          script: |
            whoami
